---
# Common playbook run on all nodes

- name: Install docker
  yum: name=docker state=present

- name: Install python-docker-py
  yum: name=python-docker-py state=present

- name: Enable docker
  systemd: enabled=yes state=started name=docker
