---
# Simple docker based Kapua setup

- name: Install httpd
  tags: httpd
  yum: name=httpd state=present

- name: Configure httpd
  template: src=kapua-vhost.conf dest=/etc/httpd/conf.d/kapua-vhost.conf
  tags: httpd
  notify: restart httpd

- name: allow apache to connect
  tags: httpd
  seboolean:
    name: httpd_can_network_connect  
    state: yes
    persistent: yes

- name: Re-create the SQL container
  tags: app
  docker_container:
    name: kapua-sql
    image: kapua/kapua-sql
    state: started
    recreate: yes
    published_ports:
      - 3306

- name: Re-create the broker container
  tags: app
  docker_container:
    name: kapua-broker
    image: kapua/kapua-broker
    state: started
    recreate: yes
    published_ports:
      - 1883
    links:
     - "kapua-sql:db"

- name: Re-create the console container
  tags: app
  docker_container:
    name: kapua-console
    image: kapua/kapua-console-jetty
    state: started
    recreate: yes
    published_ports:
      - 8080:8080
    links:
     - "kapua-sql:db"
     - "kapua-broker"

- name: Add systemd kapua-sql
  tags: systemd
  template: src=kapua-sql.service dest=/etc/systemd/system/kapua-sql.service

- name: Add systemd kapua-broker
  tags: systemd
  template: src=kapua-broker.service dest=/etc/systemd/system/kapua-broker.service

- name: Add systemd kapua-console
  tags: systemd
  template: src=kapua-console.service dest=/etc/systemd/system/kapua-console.service

- name: Activate systemd kapua-sql
  tags: systemd
  systemd:
    name: kapua-sql
    daemon_reload: yes
    state: started
    enabled: yes
    masked: no

- name: Activate systemd kapua-broker
  tags: systemd
  systemd:
    name: kapua-broker
    daemon_reload: yes
    state: started
    enabled: yes
    masked: no

- name: Activate systemd kapua-console
  tags: systemd
  systemd:
    name: kapua-console
    daemon_reload: yes
    state: started
    enabled: yes
    masked: no
